apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: ${webHookName}-cfg
  labels:
    app: ${webHookName}
webhooks:
  - name: ${webHookName}
    clientConfig:
      service:
        name: ${webHookName}-svc
        namespace: webhooks
        path: "/mutate"
      #caBundle: \${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["statefulsets",]
#    namespaceSelector:
#      matchLabels:
#        mutate-me: enabled
